name: build
on:
  push:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '14' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}
    - run: npm install -g yarn
    - run: yarn install
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '16.15.0'
    - run: npm install -g yarn
    - run: yarn install
    - uses: paambaati/codeclimate-action@v5
      env:
        CC_TEST_REPORTER_ID: 67623d19ae2b8a56286a7037297e1d9ce4420ddbafda98e58e9b18a52352554c
      with:
        coverageCommand: yarn run coverage
        debug: true
